janet-lang/jpm

bootstrap.janet
I want to package jpm for FreeBSD Ports and ran into an issue: I'm running `janet bootstrap.janet configs/bsd_config.janet` and it fails with exit status 1 even though everything was installed with no error and appears to be functional. I think this is just a typo.
=> bootstrap: Fix exit status when using override config

README.md
- sudo does not respect environment variables set prior to invocation,
switch order in README example
=> Correct environment variable order in jpm install example

jpm/shutil.janet
Solves #25
```
fatal: credential url cannot be parsed: https://github.com/janet-lang/spork.git
```
is actually output from https://github.com/git/git/blob/106298f7f9cca4158a980de149ef217751e1f943/credential.c#L512 which apparently tries to retrieve credentials upon seeing newline.
=> Trim git output

jpm/cgen.janet
This PR shows the possibility of using Janet loaders to import the cgen file and render the C source file from the template.
It also adds a new top directive, `$`, which will compile and execute code and print the result into the output file. Implementation restricts the evaluation to one form, but that would be an easy fix, and maybe it is the better way?
=> Add cgen loader and possibility to embed janet in the cgen template

jpm/cgen.janet
After #43, where I used `match` for resolving in the `emit-janet` function, I examined where we are resolving actions and concluded that for many of them, usage of `match` with the new `& rest` is a better choice. 
This PR also adds the implicit block for `while` when more than one statement is in its body.
=> Switch from case to match in cgen parsing

jpm/shutil.janet
The `shutil/copy` method converts `/` to `\\` with `(string/replace)` but that function only replaces the first instance of the pattern.
So if a path with multiple `/`s was passed to `shutil/copy` on windows `xcopy.exe` would fail.
This is PR just changes `string/replace` -> `string/replace-all`
=> shutil/copy: convert all path seperators for xcopy

jpm/commands.janet
On windows using `jpm -l deps` I got errors about "Invalid switch /i". After investigation I found that `set-tree` didn't take windows into account, so I amended that. Now I am able to use `jpm -l`. :)
=> commands/set-tree: checks if on windows, if so use \ instead of /

jpm/cgen.janet
This commit is the last part of cgen improvements on the side of the emitting code with the help of Janet. It adds the option where a tuple with the first member of type `symbol` cgen emits as one block.
I guess that would be it on this front. If you agree, I would like to add documentation for the `.cgen` usage with jpm.
=> Add chance to emit just one block from janet-emit

jpm/cgen.janet
I promised to keep the noise down with `cgen`, but the chance to emit forward fn definition is too good to pass. I hope you agree.
=> Add forward function declaration with empty body

jpm/scaffold.janet
This PR attempts to address #63 by adding a `main` function to `init-template`.
=> Address #63 Add main function to new-project output

jpm/declare.janet
I wanted to ask if something like this makes sense, because it allows a project file like this: https://github.com/saikyun/freja-jaylib/blob/test-deps/project.janet
The main idea is that I can have raylib be compiled, and added as a dependency to (freja-)jaylib. This way people won't have to recompile raylib each time jaylib is modified.
Only missing thing in jpm is linking the .a-file, so I added the `:objects`-key.
I've only tried on macOS, but should work for linux. For the sake of windows, perhaps `declare-native` / `:objects` should deal with using the right suffix. I'm also guessing that for static builds the extra `:objects` would be needed as well.
What do you think @bakpakin? :) Should I continue in this direction, and make sure it works on windows & with static builds as well, …
=> added :objects option to declare-native

jpm/commands.janet
This PR adds a `tasks` subcommand so that only rules that are tasks can be listed.
An example where this makes a difference can be seen by trying it in andrewchambers' [janet-where-defined](https://github.com/andrewchambers/janet-where-defined).
With `jpm rules`, I get:
```
$ jpm rules
/home/user/.local/lib/janet/.manifests/where-defined.jdn
build
build/_jmod_where_defined.a
build/_jmod_where_defined.meta.janet
build/_jmod_where_defined.so
build/where-defined.o
build/where-defined.static.o
clean
install
libbacktrace/.libs/libbacktrace.a
manifest
test
uninstall
```
With `jpm tasks`, I get:
```
$ jpm tasks
build
clean
install
manifest
test
uninstall
```
This can also be handy when putting together shell completion functionality as `jpm` can be queried for a list of rules that are tasks.
=> Add tasks subcommand

jpm/declare.janet
Without this fix first `jpm build` for projects with declared native from Janet code errors with:
`error: failed to open file build/src.c: No such file or directory.`
=> Add create-dirs before codegen

jpm/commands.janet, jpm/scaffold.janet
This PR is an attempt to address #74 by adding a `new-exe-project` subcommand.
It includes changes to `jpm/scaffold.janet` and `jpm/commands.janet`.
`jpm/scaffold.janet`:
* Addition of a new template named `exe-project-template`
* Change the logic a bit in `scaffold-project` to accomodate the new template
`jpm/commands.janet`:
* Modify the usage string in `help` to mention the new subcommand
* Addition of a `new-exe-project` function that invokes `scaffold/scaffold-project` appropriately
* Add key-value pair for new subcommand in `subcommands` definition
=> Address #74 - add new-exe-project subcommand

jpm/scaffold.janet
This PR attempts to address a remark made in [a discussion](https://github.com/janet-lang/janet/discussions/1054#discussioncomment-6051809) at the janet repository:
> Note: In the project.janet file in declare-executable you have to refer to the init.janet file with the folder name example/init.janet, whereas in declare-source you need to refer to src/init.janet.
I guess there is more than one way to address this including:
* Change the name of the source directory that is created
* Change the associated value for `:source` in `project.janet`
This PR took the latter path.
=> Make :source refer to existing directory

jpm/shutil.janet
This PR contains a refinement of work @tionis and I did for #71.
It includes one change to `do-monkeypatch`, specifically a tweak to the template path used:
```janet
(string build-dir ":all::native:")
```
instead of `build-dir`.
Please see [the discussion from here](https://github.com/janet-lang/jpm/issues/71#issuecomment-1581017161) for some details.  Note that the change included in this PR is slightly different (better I think), but I also tested it and got comarable good results.
=> Further address #71 - refine do-monkeypatch

jpm/cc.janet, jpm/declare.janet, jpm/make-config.janet
i noticed problems during linking, this fixed them for me
through trial and error at first i ended up using the .static.lib files during linking, it worked.
but after reading more into linking dynamic libraries on windows, i figured the .lib files are enough to link to a dll
=> developing a native module: linking against spork/tarray didnt work on windows

jpm/declare.janet, jpm/shutil.janet
Pretty simple addition. I found the output of jpm test a bit hard to parse at a glance so I added some color if the output is a tty.
=> Added colored output to jpm test is (os/isatty)

jpm/pm.janet
The `update-installed` function catches all errors raised during package updates. As a result, running `jpm update-install` will result in a zero exit code even if an error occurred. This PR continues catching these errors but then raises an error before the function returns.
Currently, the `update-installed` function catches errors that are raised by `bundle-install`. This ensures that no one failure prevents other packages from being updated. However, while `update-installed` does print stacktraces for these errors, it does not provide any indication to the calling function that errors occurred. As noted above, this means that when called from the command line with `jpm update-installed` the command returns a zero exit code.
Rather than raise an error, the function could return a value …
=> Raise error if update-installed fails

jpm/commands.janet, jpm/pm.janet
This pull request enables bundle-install to avoid reinstalling already installed packages, except when explicitly told to via either `jpm update-pkgs` or `jpm update-installed`. This enables `jpm deps` or `jpm load-lockfile` to have essentially zero cost when the packages are already installed.
Related: #82
=> allow bundle-install to avoid reinstalling an already installed package
